##
## EPITECH PROJECT, 2025
## Loop-The-Game
## File description:
## constants
##

import pygame

pygame.init()

info = pygame.display.Info()
SCREEN_WIDTH = info.current_w
SCREEN_HEIGHT = info.current_h

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (128, 128, 128)
RED = (255, 0, 0)
BLUE = (0, 0, 255)

PLAYER_HEIGHT = SCREEN_HEIGHT // 3  
PLAYER_WIDTH = int(PLAYER_HEIGHT * 0.4)
PLAYER_SPEED = SCREEN_WIDTH // 140
PLAYER_GRAVITY = 0.8
PLAYER_JUMP_POWER = -16

ROOM_WIDTH = SCREEN_WIDTH
ROOM_HEIGHT = SCREEN_HEIGHT
DOOR_WIDTH = SCREEN_WIDTH // 20
DOOR_HEIGHT = SCREEN_HEIGHT // 4

BACKGROUND_WIDTH = SCREEN_WIDTH
BACKGROUND_HEIGHT = SCREEN_HEIGHT
